export const GETPRODUCTREQUESTACTION="GETPRODUCTREQUESTACTION";
export const GETPRODUCTSUCCESSACTION="GETPRODUCTSUCCESSACTION";
export const GETPRODUCTFAILUREACTION="GETPROPRODUCTFAILUREACTION";

export const POSTPRODUCTSUCCESSACTION="POSTPRODUCTSUCCESSACTION";
export const POSTPRODUCTREQUESTACTION="POSTPRODUCTREQUESTACTION";
export const POSTPRODUCTFAILUREACTION="POSTPRODUCTFAILUREACTION";

export const PATCH_PRODUCT_REQUEST="PATCH_PRODUCT_REQUEST";
export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS";
export const PATCH_PRODUCT_FAILURE="PATCH_PRODUCT_FAILURE";
